#!/usr/bin/env bash
#
# Trust the local Caddy CA so https://localhost works without cert warnings.
#
# Why this is needed:
#   dev.sh serves the stack over https with `tls internal`, i.e. certificates
#   issued by a CA that Caddy generates locally. The browser doesn't know that
#   CA, so requests to https://localhost fail with ERR_CERT_AUTHORITY_INVALID.
#
#   Clicking "Advanced -> Proceed" is NOT a fix. That creates an exception bound
#   to one specific leaf certificate, and Caddy issues leaf certs with a ~12h
#   lifetime — so it breaks again the same day. Worse, the click-through only
#   works for top-level navigations: a fetch()/XHR (the tracker's ingest calls,
#   the user-report upload) just hard-fails with no way to accept anything.
#
#   Trusting the ROOT CA fixes it properly: the root is valid ~10 years, so every
#   leaf Caddy issues from it is trusted automatically.
#
# The CA lives in the caddy_data volume, so it survives `make dev-down`/`dev`.
# It is regenerated by `make dev-clean` (volumes dropped) — re-run this after that.
#
# Usage: make dev-trust
set -Eeuo pipefail

GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}[trust]${NC} $*"; }
warn() { echo -e "${YELLOW}[trust]${NC} $*"; }
die()  { echo -e "${RED}[trust]${NC} $*" >&2; exit 1; }

CA_PATH_IN_CONTAINER="/data/caddy/pki/authorities/local/root.crt"
TMP_CRT="$(mktemp -t caddy-local-root).crt"
trap 'rm -f "$TMP_CRT"' EXIT

docker inspect caddy >/dev/null 2>&1 || die "caddy container not running. Start the stack first: make dev"

info "Extracting Caddy local root CA..."
docker cp "caddy:${CA_PATH_IN_CONTAINER}" "$TMP_CRT" >/dev/null 2>&1 \
  || die "Could not read $CA_PATH_IN_CONTAINER from the caddy container."

SUBJECT="$(openssl x509 -in "$TMP_CRT" -noout -subject)"
NOT_AFTER="$(openssl x509 -in "$TMP_CRT" -noout -enddate)"
info "  $SUBJECT"
info "  $NOT_AFTER"

case "$(uname -s)" in
  Darwin)
    info "Installing into the macOS System keychain (sudo will prompt for your password)..."
    sudo security add-trusted-cert -d -r trustRoot \
      -k /Library/Keychains/System.keychain "$TMP_CRT"
    info "Done. Fully quit and reopen your browser for it to pick up the new trust."
    warn "Chrome/Safari/Edge use the system keychain. Firefox has its OWN trust store —"
    warn "for Firefox, import the CA via Settings -> Privacy & Security -> Certificates."
    ;;
  Linux)
    command -v update-ca-certificates >/dev/null 2>&1 \
      || die "update-ca-certificates not found; install ca-certificates."
    info "Installing into the system trust store (sudo will prompt)..."
    sudo cp "$TMP_CRT" /usr/local/share/ca-certificates/caddy-local-root.crt
    sudo update-ca-certificates
    info "Done. Restart your browser."
    warn "Chrome/Firefox on Linux use their own NSS store; if it still fails, run:"
    warn "  certutil -d sql:\$HOME/.pki/nssdb -A -t 'C,,' -n 'Caddy Local Root' -i <cert>"
    ;;
  *)
    die "Unsupported platform: $(uname -s). Trust this cert manually: $TMP_CRT"
    ;;
esac
